# generic fields same for each
ID = 0
INTERNAL_ID = 1

# indicator fields
IND_ID = 0
IND_INTERNAL_ID = 1
IND_DESCRIPTION = 2
IND_DATA_TYPE = 3
IND_DIMENSION = 4
IND_UOM = 5
IND_EXPECTED_BEHAVIOR = 6
IND_COLOR = 7

#indicator group fields
IG_ID = 0
IG_INTERNAL_ID = 1
IG_DESCRIPTION = 2
IG_INDICATOR = 3

# template fields
TEM_ID = 0
TEM_INTERNAL_ID = 1
TEM_DESCRIPTION = 2
TEM_INDICATOR_GROUP = 3

# model fields
MOD_ID = 0
MOD_INTERNAL_ID = 1
MOD_DESCRIPTION = 2
MOD_TRACKING = 3
MOD_TEMPLATE = 4
MOD_ORG = 5
