# indicator fields
IND_INTERNAL_ID = 0
IND_DESCRIPTION = 1
IND_DATA_TYPE = 2
IND_DIMENSION = 3
IND_UOM = 4
IND_EXPECTED_BEHAVIOR = 5
IND_COLOR = 6

#indicator group fields
IG_INTERNAL_ID = 0
IG_DESCRIPTION = 1
IG_INDICATOR = 2
